version: '3.9'
services:
  penx-sync-server-production:
    container_name: penx-sync-server-production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
