version: "3.9"
services:
  penx-sync-server:
    container_name: penx-sync-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
