version: '3.9'
services:
  penx-sync-server-develop:
    container_name: penx-sync-server-development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4001:4000'
    environment:
      - NODE_ENV=develop
